apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pxe-www
  name: pxe-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxe-www
  template:
    metadata:
      labels:
        app: pxe-www
    spec:
      volumes:
        - name: pxe-www-storage
          nfs: 
            server: nas.crazyzone.be 
            path: /volume1/docker-storage/pxe
      containers:
      - image: httpd:latest
        name: pxe-www
        ports:
        - containerPort: 80
          name: pxe-www
        volumeMounts:
        - name: pxe-www-storage
          mountPath: /usr/local/apache2/htdocs/